---
# tasks file for backup

  - name: copy sources.list
    template:
      src   : sources.list.j2
      dest  : /etc/apt/sources.list
      owner : root
      group : root
      mode  : '0644'
      backup: yes

  - name: install a list of basic packages
    apt:
      pkg:
      - mc
      - nfs-kernel-server
      - nfs-common
      - telnet
      - tree
      - cifs-utils
      - tcpdump
      - sudo
      - wget
      - curl
      - gnupg2
      - zip
      - rsyslog
      update_cache: yes
#      - prometheus-node-exporter      

  - name: add line 1 to /etc/hosts
    ansible.builtin.lineinfile:
      path   : /etc/hosts
      line   : '####### add to all hostfiles #######'
      create : yes
      owner  : root
      group  : root
      mode   : '0644'

  - name: add line 2 to /etc/hosts
    ansible.builtin.lineinfile:
      path   : /etc/hosts
      line   : '{{ backup }}	backup.{{ domain }}	#Backup'
      create : yes
      owner  : root
      group  : root
      mode   : '0644'

  - name: add line 3 to /etc/hosts
    ansible.builtin.lineinfile:
      path   : /etc/hosts
      line   : '{{ nginx }}	nginx.{{ domain }}		#Nginx'
      create : yes
      owner  : root
      group  : root
      mode   : '0644'

  - name: add line 4 to /etc/hosts
    ansible.builtin.lineinfile:
      path   : /etc/hosts
      line   : '{{ apache1 }}	apache1.{{ domain }}		#Apache 1'
      create : yes
      owner  : root
      group  : root
      mode   : '0644'

  - name: add line 5 to /etc/hosts
    ansible.builtin.lineinfile:
      path   : /etc/hosts
      line   : '{{ apache2 }}	apache2.{{ domain }}		#Apache 2'
      create : yes
      owner  : root
      group  : root
      mode   : '0644'

  - name: add line 6 to /etc/hosts
    ansible.builtin.lineinfile:
      path   : /etc/hosts
      line   : '{{ mysqlsrs }}	mysqlsrs.{{ domain }}	#MySQL source'
      create : yes
      owner  : root
      group  : root
      mode   : '0644'

  - name: add line 7 to /etc/hosts
    ansible.builtin.lineinfile:
      path   : /etc/hosts
      line   : '{{ mysqlrep }}	mysqlrep.{{ domain }}	#MySQL replica'
      create : yes
      owner  : root
      group  : root
      mode   : '0644'

  - name: add line 8 to /etc/hosts
    ansible.builtin.lineinfile:
      path   : /etc/hosts
      line   : '{{ monitor }}	monitor.{{ domain }}		#Monitoring'
      create : yes
      owner  : root
      group  : root
      mode   : '0644'

  - name: add line 9 to /etc/hosts
    ansible.builtin.lineinfile:
      path   : /etc/hosts
      line   : '{{ elk }}	elk.{{ domain }}		#ELK stack'
      create : yes
      owner  : root
      group  : root
      mode   : '0644'

  - name: add line 10 to /etc/hosts
    ansible.builtin.lineinfile:
      path   : /etc/hosts
      line   : '###########################'
      create : yes
      owner  : root
      group  : root
      mode   : '0644'

  - name: Download Zabbix repo package
    get_url:
      url: "https://repo.zabbix.com/zabbix/7.2/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.2+debian12_all.deb"
      dest: "/tmp/zabbix-release_latest_7.2+debian12_all.deb"

  - name: Install Zabbix repo package
    apt:
      deb: "/tmp/zabbix-release_latest_7.2+debian12_all.deb"

  - name: Zabbix agent 2 install - install 7.2 latest agent
    apt:
      pkg:
      - zabbix-agent2
      update_cache: yes

  - name: make zabbix_agent2.conf from template
    template: 
      src: zabbix_agent2.conf.j2
      dest: /etc/zabbix/zabbix_agent2.conf
      owner: root
      group: root
      mode: '644'

  - name: make zabbix_agentd.psk from template
    template: 
      src: zabbix_agentd.psk.j2
      dest: /etc/zabbix/zabbix_agentd.psk
      owner: zabbix
      group: zabbix
      mode: '400'
  
  - name: restart Zabbix agent 2
    systemd:
      unit: zabbix-agent2.service
      state: restarted
      enabled: yes
      daemon_reload: yes

  - name: create a directory if it does not exist /www
    file:
      path   : /www
      state  : directory
      mode   : '0777'

  - name: create a directory if it does not exist /backup
    file:
      path   : /backup
      state  : directory
      mode   : '0777'

  - name: create a directory if it does not exist /backup/elk
    file:
      path   : /backup/elk
      state  : directory
      mode   : '0777'

  - name: create a directory if it does not exist /backup/grafana
    file:
      path   : /backup/grafana
      state  : directory
      mode   : '0777'

  - name: create a directory if it does not exist /backup/mysql
    file:
      path   : /backup/mysql
      state  : directory
      mode   : '0777'

  - name: create a directory if it does not exist /backup/www
    file:
      path   : /backup/www
      state  : directory
      mode   : '0777'

  - name: create a directory if it does not exist /backup/zabbix
    file:
      path   : /backup/zabbix
      state  : directory
      mode   : '0777'

  - name: make /etc/exports from template
    template: 
      src: exports.j2
      dest: /etc/exports
      owner: root
      group: root
      mode: '644'

  - name: Export NFS shares
    command: exportfs -ra

  - name: Enable and start NFS server
    service:
      name: nfs-server
      state: started
      enabled: true

  - name: Copy Elastic backup
    copy:
      src   : elasticsearch_backup_2025-04-18_15-13-35.tar.gz
      dest  : /backup/elk/elasticsearch_backup_2025-04-18_15-13-35.tar.gz
      owner : root
      group : root
      mode  : '0644'

  - name: Copy Grafana backup
    copy:
      src   : backup_grafana_2025-04-11_03h-00m.zip
      dest  : /backup/grafana/backup_grafana_2025-04-11_03h-00m.zip
      owner : root
      group : root
      mode  : '0644'

  - name: Copy MySQL backup
    copy:
      src   : backup_wordpress_2025-04-11_00h-00m.tar.gz
      dest  : /backup/mysql/backup_wordpress_2025-04-11_00h-00m.tar.gz
      owner : root
      group : root
      mode  : '0644'

  - name: Copy www backup
    copy:
      src   : backup_www_2025-04-11_01h-00m.zip
      dest  : /backup/www/backup_www_2025-04-11_01h-00m.zip
      owner : root
      group : root
      mode  : '0644'

  - name: Copy Zabbix backup
    copy:
      src   : backup_zabbix_2025-04-14_13h-46m.tar.gz
      dest  : /backup/zabbix/backup_zabbix_2025-04-14_13h-46m.tar.gz
      owner : root
      group : root
      mode  : '0644'

  - name: Ensure /install_tmp directory exists
    file:
      path: /install_tmp
      state: directory
      mode: '0755'
      owner: root
      group: root  

  - name: Check file exists /install_tmp/filebeat_8.9.1_amd64.deb
    stat:
      path: /install_tmp/filebeat_8.9.1_amd64.deb
    register: filebeat_deb

  - name: Downloading filebeat_8.9.1_amd64.deb
    get_url:
      url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.9.1-amd64.deb
      dest: /install_tmp/filebeat_8.9.1_amd64.deb
      mode: '0644'
    when: not filebeat_deb.stat.exists

  - name: install Filebeat for NGINX
    apt:
      deb: /install_tmp/filebeat_8.9.1_amd64.deb

  - name: rm filebeat_8.9.1_amd64.deb file after install
    file:
      path: /install_tmp/filebeat_8.9.1_amd64.deb
      state: absent

  - name: transfer config for Filebeat
    template: 
      src: filebeat.yml.j2
      dest: /etc/filebeat/filebeat.yml
      owner: root
      group: root
      mode: '600'

  - name: restart Filebeat
    systemd:
      unit: filebeat.service
      state: restarted
      enabled: yes
      daemon_reload: yes

  - name: rm temp install directory /install_tmp
    file:
      path: /install_tmp
      state: absent
...